"""tasks table

Revision ID: 5504b97938e8
Revises: 1d6a18f2159c
Create Date: 2020-04-30 18:31:52.822729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5504b97938e8'
down_revision = '1d6a18f2159c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uri', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_task_uri'), 'task', ['uri'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_uri'), table_name='task')
    op.drop_column('task', 'uri')
    # ### end Alembic commands ###
