"""tasks table

Revision ID: 9644d24a6e6f
Revises: 5504b97938e8
Create Date: 2020-04-30 18:58:02.144739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9644d24a6e6f'
down_revision = '5504b97938e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_uri', table_name='task')
    op.drop_column('task', 'uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uri', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_task_uri', 'task', ['uri'], unique=False)
    # ### end Alembic commands ###
